version: 0.2
        
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo build started on 'date'
      - echo building WAR file
      - mvn clean
      - mvn compile
      - mvn package
  post_build:
    commands:
      - echo Build completed
      - mv target/*.war app.war
      - dir

artifacts:
  files:
    - app.war
  discard-paths: yes